/**
 * Headless tscaps CLI — generic template.
 *
 * 1. Membaca <tscaps>/templates/<name>/template.json + style.css + filters.svg
 * 2. Generate movie2short-template-bundle.generated.ts (dibaca renderer browser)
 * 3. Konversi manifest + durations -> SRT
 * 4. Vite dev server + Chromium (Playwright) -> render -> download
 *
 * Usage:
 *   TSCAPS_CHROME_PATH=<chrome.exe> npx tsx render-movie2short-template.ts \
 *     --template loki --video in.mp4 --manifest manifest.json \
 *     --durations narr.json --output out.mp4 [--width 1080 --height 1920]
 */
import path from 'node:path';
import fs from 'node:fs';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createServer, type ViteDevServer } from 'vite';
import { chromium } from 'playwright';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const EXAMPLES_ROOT = path.resolve(HERE, '..');
const PUBLIC_DIR = path.join(EXAMPLES_ROOT, 'public');
const TSCAPS_ROOT = path.resolve(EXAMPLES_ROOT, '..', '..', '..');
const TEMPLATES_ROOT = path.join(TSCAPS_ROOT, 'templates');

interface Args {
  template: string;
  video: string;
  manifest: string;
  durations: string;
  output: string;
  width: number;
  height: number;
}

const args = parseArgs(process.argv.slice(2));
run(args).catch((error) => {
  console.error('[tscaps-template-cli] FAILED:', error);
  process.exitCode = 1;
});

async function run(options: Args): Promise<void> {
  // 1. baca config template
  const tplDir = path.join(TEMPLATES_ROOT, options.template);
  const tplJsonPath = path.join(tplDir, 'template.json');
  if (!fs.existsSync(tplJsonPath)) {
    throw new Error(`Template tidak ditemukan: ${tplDir}`);
  }
  const tplJson = JSON.parse(await readFile(tplJsonPath, 'utf8'));
  const css = await readFile(path.join(tplDir, 'style.css'), 'utf8');
  const filtersSvgPath = path.join(tplDir, 'filters.svg');
  const filtersSvg = fs.existsSync(filtersSvgPath) ? await readFile(filtersSvgPath, 'utf8') : null;

  // 2. generate bundle TS
  const bundle = `// GENERATED by render-movie2short-template.ts — jangan edit manual.\n` +
    `export const TEMPLATE_ID: string = ${JSON.stringify(options.template)};\n` +
    `export const TEMPLATE_JSON: any = ${JSON.stringify(tplJson)};\n` +
    `export const TEMPLATE_CSS: string = ${JSON.stringify(css)};\n` +
    `export const TEMPLATE_FILTERS: string | null = ${JSON.stringify(filtersSvg)};\n`;
  await writeFile(path.join(HERE, 'movie2short-template-bundle.generated.ts'), bundle, 'utf8');
  console.log(`[tscaps-template-cli] bundle: ${options.template} (css ${css.length} chars${filtersSvg ? `, svg ${filtersSvg.length}` : ''})`);

  // 3. stage video + srt
  await mkdir(PUBLIC_DIR, { recursive: true });
  const stagedVideo = path.join(PUBLIC_DIR, 'movie2short-input.mp4');
  const stagedSrt = path.join(PUBLIC_DIR, 'movie2short-captions.srt');
  await copyFile(path.resolve(options.video), stagedVideo);
  const srt = await buildSrt(options.manifest, options.durations);
  await writeFile(stagedSrt, srt, 'utf8');

  const output = path.resolve(options.output);
  const srtOutput = output.replace(/\.[^.]+$/, '.srt');
  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(srtOutput, srt, 'utf8');
  console.log(`[tscaps-template-cli] SRT cues: ${(srt.match(/-->/g) ?? []).length}; wrote ${srtOutput}`);

  // 4. vite + chromium
  const server = await startServer();
  try {
    const executablePath = process.env.TSCAPS_CHROME_PATH || findBundledChrome();
    const browser = await chromium.launch({ executablePath, headless: true });
    try {
      const context = await browser.newContext({ acceptDownloads: true });
      const page = await context.newPage();
      page.on('console', (msg) => console.log(`[page ${msg.type()}] ${msg.text()}`));
      page.on('pageerror', (error) => console.error('[page error]', error.message));
      const url = `${resolveUrl(server)}cli/movie2short-renderer-template.html` +
        `?width=${options.width}&height=${options.height}&output=${encodeURIComponent(path.basename(output))}`;
      console.log(`[tscaps-template-cli] Opening ${url}`);
      await page.goto(url, { waitUntil: 'networkidle', timeout: 120_000 });
      const downloadPromise = page.waitForEvent('download', { timeout: 0 });
      await page.evaluate(() => window.renderMovie2short());
      const download = await downloadPromise;
      const downloadedPath = await download.path();
      if (!downloadedPath) throw new Error('Download produced no local path');
      await copyFile(downloadedPath, output);
      console.log(`[tscaps-template-cli] Wrote ${output}`);
    } finally {
      await browser.close();
    }
  } finally {
    await server.close();
  }
}

async function buildSrt(manifestPath: string, durationsPath: string): Promise<string> {
  const manifest = JSON.parse(await readFile(path.resolve(manifestPath), 'utf8'));
  const durationsData = JSON.parse(await readFile(path.resolve(durationsPath), 'utf8'));
  const durations = durationsData.sceneDurationsSec as number[];
  if (!Array.isArray(manifest.scenes) || !Array.isArray(durations)) {
    throw new Error('Manifest scenes and sceneDurationsSec must be arrays');
  }
  if (manifest.scenes.length !== durations.length || durations.length === 0) {
    throw new Error(`Scene/duration mismatch: ${manifest.scenes.length} scenes, ${durations.length} durations`);
  }
  let cursor = 0;
  const blocks: string[] = [];
  for (let i = 0; i < manifest.scenes.length; i++) {
    const text = String(manifest.scenes[i].narration_text).trim();
    const duration = Number(durations[i]);
    if (!Number.isFinite(duration) || duration <= 0) {
      throw new Error(`Invalid duration for scene ${i + 1}: ${String(durations[i])}`);
    }
    if (!text) throw new Error(`Scene ${i + 1} has no narration_text`);
    const start = cursor;
    const end = cursor + duration;
    blocks.push(`${i + 1}\n${toSrtTime(start)} --> ${toSrtTime(end)}\n${text}`);
    cursor = end;
  }
  return `${blocks.join('\n\n')}\n`;
}

function toSrtTime(seconds: number): string {
  const msTotal = Math.round(seconds * 1000);
  const h = Math.floor(msTotal / 3_600_000);
  const m = Math.floor((msTotal % 3_600_000) / 60_000);
  const s = Math.floor((msTotal % 60_000) / 1000);
  const ms = msTotal % 1000;
  return `${pad(h, 2)}:${pad(m, 2)}:${pad(s, 2)},${pad(ms, 3)}`;
}

function pad(value: number, width: number): string {
  return String(value).padStart(width, '0');
}

async function startServer(): Promise<ViteDevServer> {
  const server = await createServer({
    root: EXAMPLES_ROOT,
    configFile: path.join(EXAMPLES_ROOT, 'vite.config.ts'),
    server: { host: '127.0.0.1', port: 0 },
  });
  await server.listen();
  return server;
}

function resolveUrl(server: ViteDevServer): string {
  const url = server.resolvedUrls?.local?.[0];
  if (!url) throw new Error('Vite server has no local URL');
  return url;
}

function findBundledChrome(): string {
  const local = process.env.LOCALAPPDATA;
  if (!local) throw new Error('LOCALAPPDATA is unavailable');
  return path.join(local, 'ms-playwright', 'chromium-1228', 'chrome-win64', 'chrome.exe');
}

function parseArgs(argv: string[]): Args {
  const values = new Map<string, string>();
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i];
    const value = argv[i + 1];
    if (!key?.startsWith('--') || !value) throw new Error(`Invalid argument near ${key ?? '<end>'}`);
    values.set(key.slice(2), value);
  }
  const required = (name: string): string => {
    const value = values.get(name);
    if (!value) throw new Error(`Missing --${name}`);
    return value;
  };
  return {
    template: required('template'),
    video: required('video'),
    manifest: required('manifest'),
    durations: required('durations'),
    output: required('output'),
    width: Number(values.get('width') || 1080),
    height: Number(values.get('height') || 1920),
  };
}
