/**
 * Headless tscaps CLI — generic template.
 *
 * 1. Membaca <tscaps>/templates/<name>/template.json + style.css + filters.svg
 * 2. Generate movie2short-template-bundle.generated.ts (dibaca renderer browser)
 * 3. Stage video ke public dir
 * 4. Vite dev server + Chromium (Playwright) -> Whisper transcribe + render -> download
 *
 * Usage:
 *   TSCAPS_CHROME_PATH=<chrome.exe> npx tsx src/caption/render.ts \
 *     --template loki --video in.mp4 --output out.mp4 [--width 1080 --height 1920]
 */
import path from 'node:path';
import fs from 'node:fs';
import { copyFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createServer, type ViteDevServer } from 'vite';
import { chromium } from 'playwright';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const EXAMPLES_ROOT = HERE;
const PUBLIC_DIR = path.join(EXAMPLES_ROOT, 'public');
const TSCAPS_ROOT = path.resolve(EXAMPLES_ROOT, '..', '..', '..');
const TEMPLATES_ROOT = process.env.TSCAPS_TEMPLATES_DIR || path.join(TSCAPS_ROOT, 'templates');

interface Args {
  template: string;
  video: string;
  output: string;
  width: number;
  height: number;
  language?: string;
}

const args = parseArgs(process.argv.slice(2));
run(args).catch((error) => {
  console.error('[tscaps-template-cli] FAILED:', error);
  process.exitCode = 1;
});

async function run(options: Args): Promise<void> {
  // 1. baca config template
  const tplDir = path.join(TEMPLATES_ROOT, options.template);
  const tplJsonPath = path.join(tplDir, 'template.json');
  if (!fs.existsSync(tplJsonPath)) {
    throw new Error(`Template tidak ditemukan: ${tplDir}`);
  }
  const tplJson = JSON.parse(fs.readFileSync(tplJsonPath, 'utf8'));
  // Runtime studio memakai artifact .build (recipe tscaps: sudah di-expand
  // jadi primitif). File authored (style.css/filters.svg) cuma fallback.
  const cssPath = fs.existsSync(path.join(tplDir, 'style.build.css'))
    ? path.join(tplDir, 'style.build.css') : path.join(tplDir, 'style.css');
  const css = fs.readFileSync(cssPath, 'utf8');
  const filtersBuildPath = path.join(tplDir, 'filters.build.svg');
  const filtersSvgPath = fs.existsSync(filtersBuildPath) ? filtersBuildPath : path.join(tplDir, 'filters.svg');
  const filtersSvg = fs.existsSync(filtersSvgPath) ? fs.readFileSync(filtersSvgPath, 'utf8') : null;

  // 2. generate bundle TS
  // Font CSS dibaca dari disk (Node) dan ditanam ke bundle — JANGAN fetch
  // dari browser: Vite dev mengubah fetch *.css jadi modul JS HMR.
  let fontsCss = '';
  try {
    fontsCss = fs.readFileSync(path.join(HERE, 'fonts.css'), 'utf8');
  } catch { /* tanpa font embed, lanjut fallback */ }
  const bundle = `// GENERATED by render.ts — jangan edit manual.\n` +
    `export const TEMPLATE_ID: string = ${JSON.stringify(options.template)};\n` +
    `export const TEMPLATE_JSON: any = ${JSON.stringify(tplJson)};\n` +
    `export const TEMPLATE_CSS: string = ${JSON.stringify(css)};\n` +
    `export const TEMPLATE_FONTS_CSS: string = ${JSON.stringify(fontsCss)};\n` +
    `export const TEMPLATE_FILTERS: string | null = ${JSON.stringify(filtersSvg)};\n`;
  console.log(`[tscaps-template-cli] fonts.css: ${fontsCss.length} chars`);
  fs.writeFileSync(path.join(HERE, 'bundle.generated.ts'), bundle, 'utf8');
  console.log(`[tscaps-template-cli] bundle: ${options.template} (css ${css.length} chars${filtersSvg ? `, svg ${filtersSvg.length}` : ''})`);

  // 3. stage video only (Whisper akan ekstrak audio sendiri dari video blob)
  await mkdir(PUBLIC_DIR, { recursive: true });
  await copyFile(path.resolve(options.video), path.join(PUBLIC_DIR, 'input.mp4'));
  console.log(`[tscaps-template-cli] Staged video: ${options.video}`);

  const output = path.resolve(options.output);
  await mkdir(path.dirname(output), { recursive: true });

  // 4. vite + chromium
  const server = await startServer();
  try {
    const executablePath = process.env.TSCAPS_CHROME_PATH || findBundledChrome();
    const browser = await chromium.launch({ executablePath, headless: true });
    try {
      const context = await browser.newContext();
      // Transfer hasil via binding per-chunk (base64) langsung ke file output.
      // Tidak lewat pipeline download browser: rapuh saat disk sistem (C:) penuh.
      let fd: number | null = null;
      let received = 0;
      await context.exposeFunction('m2sSaveChunk', async (payload: { index: number; b64: string; last: boolean }) => {
        if (fd === null) fd = fs.openSync(output, 'w');
        const buf = Buffer.from(payload.b64, 'base64');
        fs.writeSync(fd, buf);
        received += buf.length;
        if (payload.last && fd !== null) {
          fs.closeSync(fd);
          fd = null;
        }
      });
      const page = await context.newPage();
      page.on('console', (msg) => console.log(`[page ${msg.type()}] ${msg.text()}`));
      page.on('pageerror', (error) => console.error('[page error]', error.message));
      const url = `${resolveUrl(server)}template.html` +
        `?width=${options.width}&height=${options.height}&output=${encodeURIComponent(path.basename(output))}` +
        (options.language ? `&language=${encodeURIComponent(options.language)}` : '');
      console.log(`[tscaps-template-cli] Opening ${url}`);
      try {
        await page.goto(url, { waitUntil: 'networkidle', timeout: 300_000 });
        await page.evaluate(() => window.renderMovie2short());
      } finally {
        if (fd !== null) { try { fs.closeSync(fd); } catch {} fd = null; }
      }
      console.log(`[tscaps-template-cli] Wrote ${output} (${received} bytes)`);
    } finally {
      await browser.close();
    }
  } finally {
    await server.close();
  }
}

async function startServer(): Promise<ViteDevServer> {
  const server = await createServer({
    root: EXAMPLES_ROOT,
    server: { host: '127.0.0.1', port: 0 },
  });
  await server.listen();
  return server;
}

function resolveUrl(server: ViteDevServer): string {
  const url = server.resolvedUrls?.local?.[0];
  if (!url) throw new Error('Vite server has no local URL');
  return url;
}

function findBundledChrome(): string {
  const local = process.env.LOCALAPPDATA;
  if (!local) throw new Error('LOCALAPPDATA is unavailable');
  return path.join(local, 'ms-playwright', 'chromium-1228', 'chrome-win64', 'chrome.exe');
}

function parseArgs(argv: string[]): Args {
  const values = new Map<string, string>();
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i];
    const value = argv[i + 1];
    if (!key?.startsWith('--') || !value) throw new Error(`Invalid argument near ${key ?? '<end>'}`);
    values.set(key.slice(2), value);
  }
  const required = (name: string): string => {
    const value = values.get(name);
    if (!value) throw new Error(`Missing --${name}`);
    return value;
  };
  return {
    template: required('template'),
    video: required('video'),
    output: required('output'),
    width: Number(values.get('width') || 1080),
    height: Number(values.get('height') || 1920),
    language: values.get('language') || undefined,
  };
}
